spring:
    profiles:
      active: dev

---
spring:
    profiles : dev
       
sharding:
       dataSources[0]:
             driverClassName: com.mysql.cj.jdbc.Driver
             jdbcUrl: jdbc:mysql://127.0.0.1:3306/supermarket_00?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
             username: root
             password: password
             readOnly: false
             connectionTimeout: 3000
             idleTimeout: 600000
             maxLifetime: 1800000
             maximumPoolSize: 50
       dataSources[1]:
             driverClassName: com.mysql.cj.jdbc.Driver
             jdbcUrl: jdbc:mysql://127.0.0.1:3306/supermarket_01?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
             username: root
             password: password
             readOnly: false
             connectionTimeout: 3000
             idleTimeout: 600000
             maxLifetime: 1800000
             maximumPoolSize: 50
       dataSources[2]:
             driverClassName: com.mysql.cj.jdbc.Driver
             jdbcUrl: jdbc:mysql://127.0.0.1:3306/supermarket_02?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
             username: root
             password: password
             readOnly: false
             connectionTimeout: 3000
             idleTimeout: 600000
             maxLifetime: 1800000
             maximumPoolSize: 50
       dataSources[3]:
             driverClassName: com.mysql.cj.jdbc.Driver
             jdbcUrl: jdbc:mysql://127.0.0.1:3306/supermarket_03?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
             username: root
             password: password
             readOnly: false
             connectionTimeout: 3000
             idleTimeout: 600000
             maxLifetime: 1800000
             maximumPoolSize: 50
       tableConfigs[0]:
             name: zto_enter_stock
             shardingColumn: bill_code
             #每张库中的表的数量
             size: 4
       defaultDSIndex: 0
       basePackage: com.gwg.*.mapper
       mapperLocations: classpath*:com/gwg/demo/mapper/*.xml
       typeAliasesPackage: com.gwg.*.model






